In [1]:
import pandas as pd

df = pd.read_csv('../../data/raw/hotel_bookings.csv')
df.shape

(119390, 32)

In [2]:
import sqlite3

conn = sqlite3.connect('../../data/processed/stayiq.db')
df.to_sql('bookings', conn, if_exists='replace', index=False)
print("Table created successfully")

Table created successfully

In [3]:
%load_ext sql
%sql sqlite:///../../data/processed/stayiq.db

In [4]:
%%sql
SELECT lead_time
FROM bookings
WHERE is_canceled = 1
LIMIT 10;

 * sqlite:///../../data/processed/stayiq.db
Done.

KeyError: 'DEFAULT'

In [5]:
query = """
SELECT lead_time
FROM bookings
WHERE is_canceled = 1
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

   lead_time
0         85
1         75
2         23
3         60
4         96
5         45
6         40
7         43
8         45
9         47

In [6]:
query = """
SELECT hotel, adr
FROM bookings
WHERE is_canceled = 0 AND adr > 100
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

          hotel     adr
0  Resort Hotel  107.00
1  Resort Hotel  103.00
2  Resort Hotel  145.00
3  Resort Hotel  154.77
4  Resort Hotel  107.42
5  Resort Hotel  153.00
6  Resort Hotel  108.80
7  Resort Hotel  137.00
8  Resort Hotel  123.00
9  Resort Hotel  137.00