In [ ]:
import pandas as pd

df = pd.read_csv('../../data/raw/hotel_bookings.csv')
df.shape

(119390, 32)

In [ ]:
import sqlite3

conn = sqlite3.connect('../../data/processed/stayiq.db')
df.to_sql('bookings', conn, if_exists='replace', index=False)
print("Table created successfully")

Table created successfully

In [ ]:
query = """
SELECT lead_time
FROM bookings
WHERE is_canceled = 1
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

   lead_time
0         85
1         75
2         23
3         60
4         96
5         45
6         40
7         43
8         45
9         47

In [ ]:
query = """
SELECT hotel, adr
FROM bookings
WHERE is_canceled = 0 AND adr > 100
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

          hotel     adr
0  Resort Hotel  107.00
1  Resort Hotel  103.00
2  Resort Hotel  145.00
3  Resort Hotel  154.77
4  Resort Hotel  107.42
5  Resort Hotel  153.00
6  Resort Hotel  108.80
7  Resort Hotel  137.00
8  Resort Hotel  123.00
9  Resort Hotel  137.00

In [ ]:
query = """
SELECT hotel, adr
FROM bookings
WHERE adr = 0
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

          hotel  adr
0  Resort Hotel  0.0
1  Resort Hotel  0.0
2  Resort Hotel  0.0
3  Resort Hotel  0.0
4  Resort Hotel  0.0
5  Resort Hotel  0.0
6  Resort Hotel  0.0
7  Resort Hotel  0.0
8  Resort Hotel  0.0
9  Resort Hotel  0.0

In [ ]:
query = """
SELECT hotel, lead_time
FROM bookings
WHERE lead_time > 300
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

          hotel  lead_time
0  Resort Hotel        342
1  Resort Hotel        737
2  Resort Hotel        368
3  Resort Hotel        364
4  Resort Hotel        324
5  Resort Hotel        394
6  Resort Hotel        366
7  Resort Hotel        304
8  Resort Hotel        321
9  Resort Hotel        317

In [ ]:
query = """
SELECT country
FROM bookings
WHERE country = 'PRT'
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

  country
0     PRT
1     PRT
2     PRT
3     PRT
4     PRT
5     PRT
6     PRT
7     PRT
8     PRT
9     PRT

In [ ]:
query = """
SELECT hotel, is_canceled
FROM bookings
WHERE is_canceled = 1
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

          hotel  is_canceled
0  Resort Hotel            1
1  Resort Hotel            1
2  Resort Hotel            1
3  Resort Hotel            1
4  Resort Hotel            1
5  Resort Hotel            1
6  Resort Hotel            1
7  Resort Hotel            1
8  Resort Hotel            1
9  Resort Hotel            1

In [ ]:
query = """
SELECT customer_type, adr
FROM bookings
WHERE adr > 300
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

     customer_type    adr
0        Transient  332.0
1        Transient  369.0
2        Transient  309.0
3        Transient  314.5
4        Transient  304.0
5        Transient  329.0
6        Transient  322.0
7        Transient  322.0
8  Transient-Party  340.0
9        Transient  384.0

In [ ]:
query = """
SELECT *
FROM bookings
WHERE hotel = 'City Hotel'
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,City Hotel,0,6,2015,July,27,1,0,2,1,...,No Deposit,6.0,None,0,Transient,0.00,0,0,Check-Out,2015-07-03
1,City Hotel,1,88,2015,July,27,1,0,4,2,...,No Deposit,9.0,None,0,Transient,76.50,0,1,Canceled,2015-07-01
2,City Hotel,1,65,2015,July,27,1,0,4,1,...,No Deposit,9.0,None,0,Transient,68.00,0,1,Canceled,2015-04-30
3,City Hotel,1,92,2015,July,27,1,2,4,2,...,No Deposit,9.0,None,0,Transient,76.50,0,2,Canceled,2015-06-23
4,City Hotel,1,100,2015,July,27,2,0,2,2,...,No Deposit,9.0,None,0,Transient,76.50,0,1,Canceled,2015-04-02
5,City Hotel,1,79,2015,July,27,2,0,3,2,...,No Deposit,9.0,None,0,Transient,76.50,0,1,Canceled,2015-06-25
6,City Hotel,0,3,2015,July,27,2,0,3,1,...,No Deposit,1.0,None,0,Transient-Party,58.67,0,0,Check-Out,2015-07-05
7,City Hotel,1,63,2015,July,27,2,1,3,1,...,No Deposit,9.0,None,0,Transient,68.00,0,0,Canceled,2015-06-25
8,City Hotel,1,62,2015,July,27,2,2,3,2,...,No Deposit,8.0,None,0,Transient,76.50,0,1,No-Show,2015-07-02
9,City Hotel,1,62,2015,July,27,2,2,3,2,...,No Deposit,8.0,None,0,Transient,76.50,0,1,No-Show,2015-07-02

In [ ]:
query = """
SELECT hotel, adr, customer_type
FROM bookings
WHERE is_canceled = 0 AND adr > 250
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

          hotel     adr    customer_type
0  Resort Hotel  250.33        Transient
1  Resort Hotel  280.74        Transient
2  Resort Hotel  268.00        Transient
3  Resort Hotel  252.00        Transient
4  Resort Hotel  276.43        Transient
5  Resort Hotel  277.00        Transient
6  Resort Hotel  254.00        Transient
7  Resort Hotel  252.00  Transient-Party
8  Resort Hotel  255.00        Transient
9  Resort Hotel  266.40        Transient

In [ ]:
query = """
SELECT hotel, deposit_type
FROM bookings
WHERE deposit_type = 'Non Refund' AND is_canceled = 1
LIMIT 10;
"""
result = pd.read_sql_query(query, conn)
result

          hotel deposit_type
0  Resort Hotel   Non Refund
1  Resort Hotel   Non Refund
2  Resort Hotel   Non Refund
3  Resort Hotel   Non Refund
4  Resort Hotel   Non Refund
5  Resort Hotel   Non Refund
6  Resort Hotel   Non Refund
7  Resort Hotel   Non Refund
8  Resort Hotel   Non Refund
9  Resort Hotel   Non Refund

In [ ]:
query = """
SELECT customer_type, stays_in_week_nights
FROM bookings
WHERE customer_type = 'Group' AND stays_in_week_nights > 5
LIMIT 10;
"""
result = pd.read_sql_query(query, conn)
result

  customer_type  stays_in_week_nights
0         Group                     7
1         Group                     8
2         Group                     7
3         Group                    10
4         Group                     7
5         Group                    10
6         Group                     7
7         Group                    10
8         Group                    10
9         Group                     6

In [ ]:
query = """
SELECT hotel, adr, total_of_special_requests
FROM bookings
WHERE hotel = 'Resort Hotel' AND total_of_special_requests > 2
LIMIT 10;
"""
result = pd.read_sql_query(query, conn)
result

          hotel     adr  total_of_special_requests
0  Resort Hotel   97.00                          3
1  Resort Hotel   97.00                          3
2  Resort Hotel  109.80                          3
3  Resort Hotel  109.80                          3
4  Resort Hotel  130.10                          3
5  Resort Hotel  123.00                          3
6  Resort Hotel  165.00                          3
7  Resort Hotel  125.54                          3
8  Resort Hotel   95.27                          3
9  Resort Hotel  117.90                          3

In [ ]:
query = """
SELECT is_canceled, customer_type, adr, total_of_special_requests
FROM bookings
WHERE is_canceled = 0 AND customer_type = 'Transient' AND adr > 150 AND total_of_special_requests >= 1
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

   is_canceled customer_type     adr  total_of_special_requests
0            0     Transient  154.77                          1
1            0     Transient  153.00                          1
2            0     Transient  196.54                          1
3            0     Transient  167.00                          1
4            0     Transient  164.20                          1
5            0     Transient  175.00                          1
6            0     Transient  171.32                          1
7            0     Transient  151.00                          1
8            0     Transient  157.10                          1
9            0     Transient  185.50                          1

In [ ]:
query = """
SELECT hotel, adr, customer_type
FROM bookings
WHERE is_canceled = 0
ORDER BY adr DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

          hotel     adr    customer_type
0    City Hotel  510.00        Transient
1  Resort Hotel  508.00        Transient
2    City Hotel  451.50  Transient-Party
3  Resort Hotel  426.25        Transient
4  Resort Hotel  402.00        Transient
5  Resort Hotel  397.38        Transient
6  Resort Hotel  392.00        Transient
7  Resort Hotel  388.00        Transient
8  Resort Hotel  387.00        Transient
9  Resort Hotel  383.00        Transient

In [ ]:
query = """
SELECT hotel, COUNT(*)
FROM bookings
GROUP BY hotel;
"""

result = pd.read_sql_query(query, conn)
result

          hotel  COUNT(*)
0    City Hotel     79330
1  Resort Hotel     40060

In [ ]:
query = """
SELECT country, COUNT(*)
FROM bookings
WHERE is_canceled = 1
GROUP BY country
ORDER BY COUNT(*) DESC
LIMIT 10;
"""
result = pd.read_sql_query(query, conn)
result

  country  COUNT(*)
0     PRT     27519
1     GBR      2453
2     ESP      2177
3     FRA      1934
4     ITA      1333
5     DEU      1218
6     IRL       832
7     BRA       830
8     USA       501
9     BEL       474

In [ ]:
query = """
SELECT hotel, SUM(adr)
FROM bookings
WHERE adr > 0
GROUP BY hotel
ORDER BY SUM(adr) DESC;
"""
result = pd.read_sql_query(query, conn)
result

          hotel    SUM(adr)
0    City Hotel  8353803.24
1  Resort Hotel  3803820.74

In [ ]:
query = """
SELECT customer_type, MAX(adr)
FROM bookings
WHERE hotel = 'Resort Hotel'
GROUP BY customer_type
ORDER BY MAX(adr) DESC;
"""
result = pd.read_sql_query(query, conn)
result

     customer_type  MAX(adr)
0        Transient    508.00
1  Transient-Party    367.00
2            Group    254.10
3         Contract    229.25

In [ ]:
query = """
SELECT market_segment, COUNT(*)
FROM bookings
GROUP BY market_segment;
"""
result = pd.read_sql_query(query, conn)
result

  market_segment  COUNT(*)
0       Aviation       237
1  Complementary       743
2      Corporate      5295
3         Direct     12606
4         Groups     19811
5  Offline TA/TO     24219
6      Online TA     56477
7      Undefined         2

In [ ]:
query = """
SELECT customer_type, SUM(adr)
FROM bookings
GROUP BY customer_type;
"""
result = pd.read_sql_query(query, conn)
result

     customer_type    SUM(adr)
0         Contract   356852.32
1            Group    48172.91
2        Transient  9589811.59
3  Transient-Party  2162780.78

In [ ]:
query = """
SELECT hotel, MAX(lead_time)
FROM bookings
GROUP BY hotel;
"""
result = pd.read_sql_query(query, conn)
result

          hotel  MAX(lead_time)
0    City Hotel             629
1  Resort Hotel             737

In [ ]:
query = """
SELECT deposit_type, AVG(adr)
FROM bookings
WHERE is_canceled = 0
GROUP BY deposit_type;
"""
result = pd.read_sql_query(query, conn)
result

  deposit_type    AVG(adr)
0   No Deposit  100.068209
1   Non Refund   77.578817
2   Refundable   68.635159

In [ ]:
query = """
SELECT hotel, COUNT(*)
FROM bookings
WHERE total_of_special_requests = 0
GROUP BY hotel;
"""
result = pd.read_sql_query(query, conn)
result

          hotel  COUNT(*)
0    City Hotel     47957
1  Resort Hotel     22361

In [ ]:
query = """
SELECT 
    COUNT(*) AS total_bookings,
    SUM(is_canceled) AS total_cancelled,
    ROUND(100.0 * SUM(is_canceled) / COUNT(*), 2) AS cancellation_rate_percent
FROM bookings;
"""

result = pd.read_sql_query(query, conn)
result

   total_bookings  total_cancelled  cancellation_rate_percent
0          119390            44224                      37.04

In [ ]:
query = """
SELECT 
    hotel,
    COUNT(*) AS total_bookings,
    SUM(is_canceled) AS total_cancelled,
    ROUND(100.0 * SUM(is_canceled) / COUNT(*), 2) AS cancellation_rate_percent
FROM bookings
GROUP BY hotel;
"""

result = pd.read_sql_query(query, conn)
result

          hotel  total_bookings  total_cancelled  cancellation_rate_percent
0    City Hotel           79330            33102                      41.73
1  Resort Hotel           40060            11122                      27.76

In [ ]:
query = """
SELECT 
    ROUND(SUM(adr), 2) AS revenue_lost_to_cancellations
FROM bookings
WHERE is_canceled = 1;
"""

result = pd.read_sql_query(query, conn)
result

   revenue_lost_to_cancellations
0                     4641942.67

In [ ]:
query = """
SELECT 
    is_canceled,
    ROUND(AVG(lead_time), 1) AS avg_lead_time
FROM bookings
GROUP BY is_canceled;
"""

result = pd.read_sql_query(query, conn)
result

   is_canceled  avg_lead_time
0            0           80.0
1            1          144.8

In [ ]:
query = """
SELECT 
    deposit_type,
    COUNT(*) AS total_bookings,
    SUM(is_canceled) AS total_cancelled,
    ROUND(100.0 * SUM(is_canceled) / COUNT(*), 2) AS cancellation_rate_percent
FROM bookings
GROUP BY deposit_type
ORDER BY cancellation_rate_percent DESC;
"""

result = pd.read_sql_query(query, conn)
result

  deposit_type  total_bookings  total_cancelled  cancellation_rate_percent
0   Non Refund           14587            14494                      99.36
1   No Deposit          104641            29694                      28.38
2   Refundable             162               36                      22.22

In [ ]:
query = """
SELECT 
    market_segment,
    COUNT(*) AS total_bookings,
    SUM(is_canceled) AS total_cancelled,
    ROUND(100.0 * SUM(is_canceled) / COUNT(*), 2) AS cancellation_rate_percent
FROM bookings
GROUP BY market_segment
ORDER BY cancellation_rate_percent DESC;
"""

result = pd.read_sql_query(query, conn)
result

  market_segment  total_bookings  total_cancelled  cancellation_rate_percent
0      Undefined               2                2                     100.00
1         Groups           19811            12097                      61.06
2      Online TA           56477            20739                      36.72
3  Offline TA/TO           24219             8311                      34.32
4       Aviation             237               52                      21.94
5      Corporate            5295              992                      18.73
6         Direct           12606             1934                      15.34
7  Complementary             743               97                      13.06

In [ ]:
df.to_csv('../../data/processed/bookings_clean.csv', index=False)
print("Exported successfully")

Exported successfully

In [ ]:
query = """
SELECT customer_type, ROUND(SUM(adr), 2) AS total_revenue
FROM bookings
GROUP BY customer_type
ORDER BY total_revenue DESC;
"""

result = pd.read_sql_query(query, conn)
result

     customer_type  total_revenue
0        Transient     9589811.59
1  Transient-Party     2162780.78
2         Contract      356852.32
3            Group       48172.91

In [ ]:
query1 = """
SELECT 
    COUNT(*) AS total_bookings,
    SUM(is_canceled) AS total_cancelled,
    ROUND(100.0 * SUM(is_canceled) / COUNT(*), 2) AS cancellation_rate_percent
FROM bookings;
"""
print(pd.read_sql_query(query1, conn))

   total_bookings  total_cancelled  cancellation_rate_percent
0          119390            44224                      37.04

In [ ]:
query2 = """
SELECT 
    hotel,
    COUNT(*) AS total_bookings,
    SUM(is_canceled) AS total_cancelled,
    ROUND(100.0 * SUM(is_canceled) / COUNT(*), 2) AS cancellation_rate_percent
FROM bookings
GROUP BY hotel;
"""
print(pd.read_sql_query(query2, conn))

          hotel  total_bookings  total_cancelled  cancellation_rate_percent
0    City Hotel           79330            33102                      41.73
1  Resort Hotel           40060            11122                      27.76

In [ ]:
query4 = """
SELECT 
    is_canceled,
    ROUND(AVG(lead_time), 1) AS avg_lead_time
FROM bookings
GROUP BY is_canceled;
"""
print(pd.read_sql_query(query4, conn))

   is_canceled  avg_lead_time
0            0           80.0
1            1          144.8

In [ ]:
query3 = """
SELECT 
    ROUND(SUM(adr), 2) AS revenue_lost_to_cancellations
FROM bookings
WHERE is_canceled = 1;
"""
print(pd.read_sql_query(query3, conn))

   revenue_lost_to_cancellations
0                     4641942.67

In [ ]:
query7 = """
SELECT 
    customer_type, 
    ROUND(SUM(adr), 2) AS total_revenue
FROM bookings
GROUP BY customer_type
ORDER BY total_revenue DESC;
"""
print(pd.read_sql_query(query7, conn))

     customer_type  total_revenue
0        Transient     9589811.59
1  Transient-Party     2162780.78
2         Contract      356852.32
3            Group       48172.91

In [ ]:
qA = """
SELECT
  ROUND(SUM(adr * (stays_in_weekend_nights + stays_in_week_nights)), 2) AS exposure_with_stay
FROM bookings
WHERE is_canceled = 1;
"""
print(pd.read_sql_query(qA, conn))

   exposure_with_stay
0         16727237.12

In [ ]:
qB = """
SELECT
  customer_type,
  ROUND(SUM(adr * (stays_in_weekend_nights + stays_in_week_nights)), 2) AS realised_revenue
FROM bookings
WHERE is_canceled = 0
GROUP BY customer_type
ORDER BY realised_revenue DESC;
"""
print(pd.read_sql_query(qB, conn))

     customer_type  realised_revenue
0        Transient       19332636.95
1  Transient-Party        5055351.23
2         Contract        1484917.13
3            Group         123355.10